services:
  - type: web
    name: eyed
    runtime: python
    rootDir: Eye-D
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn eyed_backend.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: "8000"
